### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [nasteazav/grid-template-init-project#1]
1)
непонятная полоса
![image](https://user-images.githubusercontent.com/8464662/93808116-3f705400-fc54-11ea-9219-91b7502a0c59.png)

2)
невалидный код
![image](https://user-images.githubusercontent.com/8464662/93808166-4c8d4300-fc54-11ea-9ae5-7d4414f12bc1.png)

3)
невалидный стиль
![image](https://user-images.githubusercontent.com/8464662/93808220-5ca52280-fc54-11ea-9206-59cf8cdf9e91.png)

4)
некорректные размеры сетки
![image](https://user-images.githubusercontent.com/8464662/93808264-6c246b80-fc54-11ea-8ab2-b1f10da7a752.png)

5)
неправильные размеры и отступы заголовка
![image](https://user-images.githubusercontent.com/8464662/93808306-7a728780-fc54-11ea-875c-5bfff68904ec.png)

**Comment by nasteazav** [comment]
Вроде все поправила

**Comment by Alecto** [comment]
пришлите две ссылки для проверки.
и, в письме отсутствует имя и группа, поэтому не понимаю, чью работу сейчас
проверяю.

вт, 22 вер. 2020 о 21:21 nasteazav <notifications@github.com> пише:
