### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [nasteazav/grid-template-init-project#2]
1)
нет соответствия макету
![image](https://user-images.githubusercontent.com/8464662/94052612-d7e80f00-fde1-11ea-8537-19d9ad7d6d59.png)

2
![image](https://user-images.githubusercontent.com/8464662/94052720-ff3edc00-fde1-11ea-9bae-6220c8aa6a32.png)
![image](https://user-images.githubusercontent.com/8464662/94052732-05cd5380-fde2-11ea-9453-a3a873c0c156.png)

**Comment by nasteazav** [comment]
Исправила.

**Comment by Alecto** [comment]
две ссылочки пожалуйста,

чт, 24 вер. 2020 о 14:49 nasteazav <notifications@github.com> пише:

**Comment by nasteazav** [comment]
https://github.com/nasteazav/grid-template-init-project.git
https://nasteazav.github.io/grid-template-init-project/

**Comment by Alecto** [comment]
все отлично, работа принята.

чт, 24 вер. 2020 о 16:57 Анастасия Завальная <notifications@github.com>
пише:
